apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/andreyev/lhc-infra.git
        targetRevision: add_roles
        directories:
          - path: roles/*
  template:
    metadata:
      name: '{{path.basename}}-appset'
    spec:
      project: default
      source:
        repoURL: https://github.com/andreyev/lhc-infra.git
        targetRevision: add_roles
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

