name: Insert GitHub URL in Markdown

on:
  push:
    branches: ['**']

jobs:
  add-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set GitHub URL and inject it
        run: |
          GH_ACCOUNT="${{ github.repository }}"
          GH_BRANCH="${{ github.ref_name }}"

          find . -type f -name \*-template | while read FILE; do
            cp ${FILE} ${FILE%%-template}
            sed -i "s|{{GH_ACCOUNT}}|${GH_ACCOUNT}|g" ${FILE%%-template}
            sed -i "s|{{GH_BRANCH}}|${GH_BRANCH}|g" ${FILE%%-template}
          done

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Fix repo URL and branch" || echo "No changes to commit"
          git push
