apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-of-appsets
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - path: applicationsets/auth
          - path: applicationsets/billing
          - path: applicationsets/observability
  template:
    metadata:
      name: '{{path.basename}}-appset'
    spec:
      project: default
      source:
        repoURL: "${REPO_URL}"
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
